# Site Config
name: "IBM Make Lab"
description: The Make Lab is a maker space at IBM, providing IBMers in Austin with the means to take a creative break and make something with their hands.
baseurl: "/"
url: https://ibmmakelab.com

# Build Settings
markdown: kramdown
highlighter: true
permalink: pretty

# In/ Excludes
include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json", "local_config.yml", "README.md"]

# Plugins
assets:
  digest: true
  cache: false
  sources:
    - "_site/assets"

# Read and Output Collections
collections:
  archive:
    output: true
    permalink: /archive/:path/
